#!/bin/bash
set -euf -o pipefail

DC="http://purl.org/dc/elements/1.1/"
NAMESPACE="http://u1087.univ-nantes.fr/"
PREFIX="my"
PRE_PROCESS="0"
POST_PROCESS="0"
RAPPER_BIN="rapper"
RDFPROC_BIN="rdfproc"
declare -a CUSTOMTRIPLES
declare -a PREREQUISITES 

function warning
	{
	echo "[Prov:Warning] $1" 1>&2
	}

function die
	{
	echo "[Prov:Error] $1" 1>&2
    exit -1
	}
#
# http://stackoverflow.com/questions/3915040
#
function abspath
	{
	echo -n "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
	}

#
# arg 1 : rdffile
#
function add_stmt
	{
	local tmpfile="${1}.tmp${RANDOM}"
	local rdfprocparam="--quiet --storage file ${tmpfile}"
	
	if [ ! -f "${1}" ]; then
    	die "Add statement: File ${1} not found!"
	fi
	
	${RDFPROC_BIN}  ${rdfprocparam}  parse "$1"
	
	if [ "$#" -eq 4 ]
	then
		${RDFPROC_BIN} ${rdfprocparam}  add "$2" "$3" "$4"	
	elif [ "$#" -eq 6 ]
	then
		echo ">>>" "$2" "$3" "$4" "$5" "$6"
		${RDFPROC_BIN} ${rdfprocparam} add-typed "$2" "$3" "$4" "$5" "$6"
	else
		rm "${tmpfile}"
		die "add_stmt:Illegal number of arguments '$#' : '$@'"
	fi

 	"${RAPPER_BIN}" --output rdfxml-abbrev --quiet "${tmpfile}" > "${1}"
	rm "${tmpfile}"
	}

#
# arg 1 : rdffile
# arg 2 : subject-uri
#
function process_custom_triples
	{
	local path="$(abspath $2)"
	for ((i=0; i<${#CUSTOMTRIPLES[*]}; i+=2));
	do
		add_stmt "${1}" "file://${path}" ${CUSTOMTRIPLES[i]} ${CUSTOMTRIPLES[i+1]}
	done
	
	for i in "${PREREQUISITES[@]}"
	do
		read -a deps <<< "${i}"
		for j in "${deps[@]}"
		do
			local deppath="$(abspath ${j})"
	
			add_stmt "${1}" "file://${path}" "${NAMESPACE}hasPrerequisites" "file://${deppath}"
		done
	
	done
	
	}

function process_start_file
	{
	local path="$(abspath $1)"
	local rdffile="${path}.rdf"
	local currdir="$(dirname ${path})"
	
	echo -e "@prefix  dc: <${DC}> .\n@prefix  ${PREFIX}: <${NAMESPACE}> .\n<file://${path}> a  ${PREFIX}:File ." |\
		"${RAPPER_BIN}" --output rdfxml-abbrev --quiet --input-uri "file://${currdir}"  -i turtle  - > "${rdffile}"
	add_stmt "${rdffile}" "file://${path}" "${NAMESPACE}start" "$(date +'%Y-%M-%dT%H:%M:%S')" "en" "http://www.w3.org/2001/XMLSchema#dateTime"
	add_stmt "${rdffile}" "file://${path}" "${NAMESPACE}author" "${NAMESPACE}users/$(whoami)"
	}


function process_finished_file
	{
	local path="$(abspath $1)"
	local rdffile="${path}.rdf"

	if [ ! -f "${path}" ]; then
    	warning "Src File ${path} not found!"
	else
		add_stmt "${rdffile}" "file://${path}" "${NAMESPACE}end" "$(date --reference=${path} +'%Y-%M-%dT%H:%M:%S')" "en" "http://www.w3.org/2001/XMLSchema#dateTime"
		add_stmt "${rdffile}" "file://${path}" "${NAMESPACE}sha" "$(sha1sum "${path}" | cut -d ' ' -f1)"
		add_stmt "${rdffile}" "file://${path}" "${NAMESPACE}size" "$(stat --printf="%s" ${path})"
	fi
	}

function prov
	{
	local path="$(abspath $1)"
	local rdffile="${path}.rdf"
	local tmppath="${rdffile}~"
	
	if [ "${PRE_PROCESS}" -eq 1 ] &&  [ "${POST_PROCESS}" -eq 1 ]; then
    	die "both --pre and --post defined."
	fi
	
	if [ "${PRE_PROCESS}" -eq 1 ] ; then
		process_start_file "$1"
		process_custom_triples "${rdffile}" "$1"
    	return
	fi
	if [ "${POST_PROCESS}" -eq 1 ] ; then
		process_finished_file "$1"
		process_custom_triples "${rdffile}" "$1"
    	return
	fi
	
	process_start_file "$1"
	process_finished_file "$1"
	process_custom_triples "${rdffile}" "$1"
	}

while [[ $# > 1 ]]
do
key="$1"
case $key in
    --)
    shift
    break
    ;;
    -B|--pre)
    PRE_PROCESS="1"
    shift # past argument
    ;;
    --rapper)
    RAPPER_BIN="$2"
    shift
    shift
    ;;
    --rapper)
    RDFPROC_BIN="$2"
    shift
    shift
    ;;
     --stmt)
    CUSTOMTRIPLES+=("$2")
    CUSTOMTRIPLES+=("$3")
    shift
    shift
    shift
    ;;
    -d|--prerequisites)
    PREREQUISITES+=("$2")
    shift
    shift
    ;;   
    *)
    break
    ;;
esac
done

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    ##exit -1
fi

for f in $*
do
  echo "Processing ${f} $# file..."
  prov "${f}"
done
